import {installReportPrint} from './print-report.js?v=20261002-3';
const escapeText=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const nf=new Intl.NumberFormat('ko-KR',{maximumFractionDigits:0});
const decimal=new Intl.NumberFormat('ko-KR',{maximumFractionDigits:2});
const amount=(n,currency='KRW')=>n===null||n===undefined?'—':(currency==='KRW'?nf:decimal).format(n);
const signed=n=>(n>0?'+':'')+amount(n);
const color=n=>n<0?'negative':n>0?'positive':'';
const date=s=>s.replaceAll('-','.');
const e=escapeText;
export function renderReport(root,report){
 let pinned=false,anchor=null,timer=null;
 const controller=new AbortController();
 const listen=(type,fn,options={})=>root.addEventListener(type,fn,{...options,signal:controller.signal});
 root.replaceChildren();
 const assets=report.summary.find(s=>s.key==='assets');
 const cashSubtotal=report.subtotal.find(s=>s.label==='원화 소계');
 root.innerHTML=`<article class="cash-document"><div class="report-heading"><div><span class="report-brand">${e(report.company)} · WEEKLY CASH REPORT</span><h1>${e(report.title)}</h1><p>${date(report.start)} ~ ${date(report.end)}</p></div><span class="report-sheet">${e(report.sheet)}</span></div>
 <div class="metric-grid"><div class="metric"><span>자산 총계</span><strong>${amount(assets.current)}<small>원</small></strong></div><div class="metric"><span>전주 대비</span><strong class="${color(assets.change)}">${signed(assets.change)}<small>원</small></strong></div><div class="metric"><span>금주 입금 · 원화</span><strong class="positive">${amount(cashSubtotal.in)}<small>원</small></strong></div><div class="metric"><span>금주 출금 · 원화</span><strong class="negative">${amount(cashSubtotal.out)}<small>원</small></strong></div></div>
 <p class="interaction-guide"><span class="guide-dot"></span>입출금 금액에 마우스를 올리면 주요 거래, <span class="mini-tag">추이</span>에 올리면 그래프가 나옵니다. 클릭하면 고정됩니다.</p>
 <section class="report-section"><div class="section-title"><h2>자금 입출금 요약</h2><span>원화: 원 · 외화: 해당 통화</span></div><div class="table-scroll"><table class="account-table"><thead><tr><th>은행</th><th>계좌 구분</th><th>계좌번호</th><th>주초잔액</th><th class="income-header">입금액</th><th class="outcome-header">출금액</th><th>주말잔액</th><th>비고</th></tr></thead><tbody>${report.rows.filter(row=>row.in||row.out).sort((a,b)=>Math.max(b.in,b.out)-Math.max(a.in,a.out)).map(row=>`<tr><td>${e(row.bank)}</td><td>${e(row.type)}${row.currency!=='KRW'?`<span class="currency">${row.currency}</span>`:''}</td><td class="account-mask">${e(row.account)}</td><td class="numeric">${amount(row.previous,row.currency)}</td>${['in','out'].map(dir=>`<td class="numeric">${row[dir]>0?`<button class="amount-button ${dir==='in'?'income':'outcome'}" data-transaction="${e(row.id)}:${dir}" aria-label="${e(row.bank+' '+row.type+' '+(dir==='in'?'입금':'출금')+' 주요 거래')}" aria-haspopup="dialog">${amount(row[dir],row.currency)}<span class="detail-dot" aria-hidden="true"></span></button>`:'—'}</td>`).join('')}<td class="numeric balance">${amount(row.current,row.currency)}</td><td class="notes">${e(row.note)}</td></tr>`).join('')}
 ${report.subtotal.map(s=>`<tr class="subtotal ${s.label.includes('합계')?'total-row':''}"><th colspan="3">${e(s.label)}</th><td class="numeric">${amount(s.previous,s.currency)}</td><td class="numeric">${s.in===null?'—':amount(s.in,s.currency)}</td><td class="numeric">${s.out===null?'—':amount(s.out,s.currency)}</td><td class="numeric balance">${s.key?`<button class="chart-button" data-chart="${s.key}" aria-label="${e(s.label)} 추이" aria-haspopup="dialog">${amount(s.current,s.currency)}<span class="mini-tag">추이</span></button>`:amount(s.current,s.currency)}</td><td>${s.currency==='KRW'?'원':s.currency}</td></tr>`).join('')}</tbody></table></div></section>
 <section class="report-section"><div class="section-title"><h2>주식보유 현황</h2><span>단위: 주, 원</span></div><div class="table-scroll"><table><thead><tr><th>구분</th><th>증권사</th><th>보유주식수</th><th>주당 가격</th><th>이전주 총액</th><th>금주 총액</th><th>차액</th><th>비고</th></tr></thead><tbody>${report.stocks.map(s=>`<tr><td>${e(s.name)}</td><td>${e(s.broker)}</td><td class="numeric">${amount(s.quantity)}</td><td class="numeric">${amount(s.price)}</td><td class="numeric">${amount(s.previous)}</td><td class="numeric balance">${amount(s.current)}</td><td class="numeric ${color(s.change)}">${signed(s.change)}</td><td class="notes">${e(s.note)}</td></tr>`).join('')}<tr class="total-row"><th colspan="4">합계</th><td class="numeric">${amount(report.stockTotal.previous)}</td><td class="numeric"><button class="chart-button" data-chart="stocks" aria-label="주식 총액 추이" aria-haspopup="dialog">${amount(report.stockTotal.current)}<span class="mini-tag">추이</span></button></td><td class="numeric ${color(report.stockTotal.change)}">${signed(report.stockTotal.change)}</td><td></td></tr></tbody></table></div></section>
 <section class="report-section summary-section"><div class="section-title"><h2>자금 총액비교 현황</h2><span>단위: 원</span></div><div class="table-scroll"><table class="summary-table"><thead><tr><th>구분</th><th>이전주</th><th>금주</th><th>차액</th></tr></thead><tbody>${report.summary.map(s=>`<tr class="${s.key==='assets'?'grand-total':''}"><th>${e(s.label)}</th><td class="numeric">${amount(s.previous)}</td><td class="numeric"><button class="chart-button" data-chart="${s.key}" aria-label="${e(s.label)} 추이" aria-haspopup="dialog">${amount(s.current)}<span class="mini-tag">추이</span></button></td><td class="numeric ${color(s.change)}">${signed(s.change)}</td></tr>`).join('')}</tbody></table></div></section>
 <footer class="report-footer"><span>입출금 설명: ${e(report.source.daily||'일일내역 미연결')} · 추이: ${e(report.source.graph||'주간 비교')}</span><span>${e(report.privacy)}</span></footer>
 ${report.warnings.length?`<details class="source-notes"><summary>자료 연결 참고사항 (${report.warnings.length})</summary><ul>${report.warnings.map(w=>`<li>${e(w)}</li>`).join('')}</ul></details>`:''}</article><aside class="report-popover" role="dialog" aria-label="보고서 상세" hidden><div class="popover-bar"><span class="popover-kind"></span><button class="popover-close" aria-label="상세 닫기">×</button></div><div class="popover-content"></div><p class="popover-hint">클릭하면 고정 · Esc로 닫기</p></aside>`;
 const paperCleanup=installReportPrint(root,report);
 const pop=root.querySelector('.report-popover'),body=pop.querySelector('.popover-content');
 function hide(){pop.hidden=true;pinned=false;anchor?.setAttribute('aria-expanded','false');anchor=null;clearTimeout(timer);}
 function place(){if(!anchor||pop.hidden)return;const rect=anchor.getBoundingClientRect(),width=Math.min(470,innerWidth-24);pop.style.width=width+'px';const height=pop.offsetHeight;let left=Math.max(12,Math.min(rect.left,innerWidth-width-12)),top=rect.bottom+8;if(top+height>innerHeight-12)top=Math.max(12,rect.top-height-8);pop.style.left=left+'px';pop.style.top=top+'px';pop.style.maxHeight=Math.max(180,innerHeight-24)+'px';}
 function open(button,lock=false){clearTimeout(timer);if(pinned&&!lock&&button!==anchor)return;if(anchor)anchor.setAttribute('aria-expanded','false');anchor=button;pinned=lock;button.setAttribute('aria-expanded','true');
  if(button.dataset.transaction){const[id,dir]=button.dataset.transaction.split(':'),row=report.rows.find(r=>r.id===id),d=row.details?.[dir];pop.querySelector('.popover-kind').textContent=dir==='in'?'금주 주요 입금':'금주 주요 출금';body.innerHTML=`<h3>${e(row.bank)} · ${e(row.type)}</h3><p class="trade-message">${e(d?.message||'연결된 일일 거래내역이 없습니다.')}</p>${d?.items?.length?`<ol class="trade-items">${d.items.map(t=>`<li><div><strong>${e(t.label)}</strong><small>${e(t.date)} · ${e(t.source)}</small></div><span>${amount(t.amount,row.currency)}<small>${row.currency==='KRW'?'원':row.currency}</small></span></li>`).join('')}</ol>`:''}<p class="detail-scope">${e(d?.scope||'일일내역 미연결')}${d?.count?` · ${d.count}건 중 상위 ${d.items.length}건`:''}</p>`;
  }else{const key=button.dataset.chart,labels={cash:'현금',foreign:'외화',stocks:'주식',assets:'자산 총계',cashForeign:'현금·외화 합계'},points=report.history.map(p=>({...p,value:key==='cashForeign'?p.cash+p.foreign:p[key]})).filter(p=>Number.isFinite(p.value)).slice(-12);pop.querySelector('.popover-kind').textContent='자금 추이';body.innerHTML=`<h3>${e(labels[key])}</h3>${chart(points,labels[key])}`;}
  pop.hidden=false;pop.querySelector('.popover-hint').textContent=lock?'상세 고정 중 · Esc로 닫기':'클릭하면 고정 · Esc로 닫기';place();
 }
 const trigger=target=>target instanceof Element?target.closest('[data-transaction],[data-chart]'):null;
 listen('mouseover',event=>{const b=trigger(event.target);if(b&&!b.contains(event.relatedTarget))open(b);});
 listen('mouseout',event=>{if(pinned)return;if((anchor?.contains(event.target)||pop.contains(event.target))&&!anchor?.contains(event.relatedTarget)&&!pop.contains(event.relatedTarget)){clearTimeout(timer);timer=setTimeout(hide,180);}});
 pop.addEventListener('mouseenter',()=>clearTimeout(timer));pop.addEventListener('mouseleave',()=>{if(!pinned)timer=setTimeout(hide,180);});
 listen('focusin',event=>{const b=trigger(event.target);if(b)open(b);});
 listen('focusout',event=>{if(!pinned&&!pop.contains(event.relatedTarget)&&!trigger(event.relatedTarget))hide();});
 listen('click',event=>{const b=trigger(event.target);if(b){if(anchor===b&&pinned)hide();else open(b,true);}else if(!pop.contains(event.target))hide();});
 pop.querySelector('.popover-close').addEventListener('click',hide);
 listen('keydown',event=>{if(event.key==='Escape')hide();});
 listen('scroll',place,{capture:true});window.addEventListener('resize',place);window.addEventListener('scroll',place,{passive:true});
 return ()=>{paperCleanup();hide();controller.abort();window.removeEventListener('resize',place);window.removeEventListener('scroll',place);};
}
function chart(points,label){
 if(points.length<2)return'<p class="empty-chart">추이를 표시하려면 두 시점 이상의 데이터가 필요합니다.</p>';
 const w=430,h=185,left=54,right=16,top=18,bottom=34;let lo=Math.min(...points.map(p=>p.value)),hi=Math.max(...points.map(p=>p.value));const pad=Math.max((hi-lo)*.15,Math.abs(hi)*.002,1);lo=Math.max(0,lo-pad);hi+=pad;
 const x=i=>left+i/(points.length-1)*(w-left-right),y=v=>top+(hi-v)/(hi-lo)*(h-top-bottom),path=points.map((p,i)=>`${i?'L':'M'}${x(i).toFixed(2)},${y(p.value).toFixed(2)}`).join(' '),baseline=h-bottom;
 const ticks=[lo,(lo+hi)/2,hi];const first=points[0],last=points.at(-1),change=last.value-first.value;
 return`<div class="chart-summary"><strong>${amount(last.value)}<small>원</small></strong><span class="${color(change)}">기간 증감 ${signed(change)}원</span></div><svg class="trend-chart" viewBox="0 0 ${w} ${h}" role="img" aria-label="${e(label)} ${first.date}부터 ${last.date}까지 추이"><title>${e(label)} 추이. ${amount(first.value)}원에서 ${amount(last.value)}원</title>${ticks.map(v=>`<line x1="${left}" y1="${y(v)}" x2="${w-right}" y2="${y(v)}" stroke="#e8edf3"/><text x="${left-8}" y="${y(v)+4}" text-anchor="end">${decimal.format(v/1e8)}</text>`).join('')}<text x="5" y="11">억원</text><path d="${path} L${x(points.length-1)},${baseline} L${left},${baseline} Z" fill="#e9f0ff"/><path d="${path}" fill="none" stroke="#285ac5" stroke-width="2.5"/>${points.map((p,i)=>`<circle cx="${x(i)}" cy="${y(p.value)}" r="${i===points.length-1?4:3}" fill="#285ac5"><title>${p.date}: ${amount(p.value)}원</title></circle>`).join('')}<text x="${left}" y="${h-10}">${first.date.slice(5)}</text><text x="${w-right}" y="${h-10}" text-anchor="end">${last.date.slice(5)}</text></svg><p class="chart-period">${date(first.date)} ~ ${date(last.date)} · 최근 ${points.length}개 시점</p><details class="chart-values"><summary>시점별 금액</summary><div>${points.map(p=>`<p><span>${date(p.date)}</span><strong>${amount(p.value)}원</strong></p>`).join('')}</div></details>`;
}
